apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    #ingress.bluemix.net/ALB-ID: private-cr7a9b181c82674f478e461c648c3000da-alb1
    ingress.bluemix.net/redirect-to-https: "True"
  name: zcp-estimate-ui-ingress
  namespace: zcp-system
spec:
  tls:
  - hosts:
    - pog-dev-estimate.cloudzcp.io
    secretName: cloudzcp-io-cert
  rules:
  - host: pog-dev-estimate.cloudzcp.io
    http:
      paths:
      - backend:
          serviceName: zcp-estimate-ui
          servicePort: 80
